version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      DEBUG: "True"
      SECRET_KEY: "django-insecure-abc123xyz"
    depends_on:
      - redis


  redis:
    image: redis:alpine
    container_name: redis_container

